### ISSUE TITLE
SofarSolar addon not working

### ISSUE THREAD

**Issue by bd-casemod** [pawelka/hassio-addons#14]
The sofarsolar addon is not working here, i'm receiving the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/inverter/__main__.py", line 1, in <module>
    import Inverter
  File "/inverter/Inverter.py", line 10, in <module>
    import anyconfig
  File "/usr/local/lib/python2.7/site-packages/anyconfig/__init__.py", line 24, in <module>
    from .api import (
  File "/usr/local/lib/python2.7/site-packages/anyconfig/api.py", line 91, in <module>
    import anyconfig.dicts
  File "/usr/local/lib/python2.7/site-packages/anyconfig/dicts.py", line 280
    raise ValueError("Wrong merge strategy: %r" % strategy) from exc
                                                               ^
SyntaxError: invalid syntax

**Comment by sztof** [comment]
Same here, after update from 1.0 to 1.1 the addon doesn't work anymore

**Comment by craigmcewen** [comment]
Same again, the update breaks the component. Can you please re-anable v1.0 as the current to get the component working again at all?

**Comment by chopperpl** [comment]
Same problem with initial install. The add-on won't start. I hope this can be fixed soon.
Dziękuje ;)

**Comment by Roberttar** [comment]
the same for me. V1.1 dosen't work

**Comment by TomaszCwik** [comment]
Same here

**Comment by cmsteinBR** [comment]
Same here, after update to V1.1 the addon doesn't work anymore.
Thank you very much for your work.

**Comment by tompython-ncg** [comment]
Same here, after update to V1.1 the addon doesn't work anymore.

**Comment by chopperpl** [comment]
It seems the code has been abandoned, so I suggest you remove it and look for an alternative solution.

**Comment by cmsteinBR** [comment]
I don't think it's abandoned: https://community.home-assistant.io/t/sofarsolar-inverter-integration/182845/25

**Comment by chopperpl** [comment]
The owner has not responded on github or HA with a single post for some time now, so to me it is abandoned.

**Comment by dr-azbest** [comment]
Same here!

**Comment by HeartandHana** [comment]
same here! Please advise me. I found the error msg below.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/inverter/__main__.py", line 1, in <module>
    import Inverter
  File "/inverter/Inverter.py", line 10, in <module>
    import anyconfig
  File "/usr/local/lib/python2.7/site-packages/anyconfig/__init__.py", line 23, in <module>
    from .api import (
  File "/usr/local/lib/python2.7/site-packages/anyconfig/api/__init__.py", line 86, in <module>
    from .datatypes import MaybeDataT
  File "/usr/local/lib/python2.7/site-packages/anyconfig/api/datatypes.py", line 10, in <module>
    from ..backend import base
  File "/usr/local/lib/python2.7/site-packages/anyconfig/backend/__init__.py", line 25
    PARSERS: ParserClssT = [
           ^
SyntaxError: invalid syntax

**Comment by loki29pl** [comment]
Same issue here on the newest HomeAssistant. Any chances to fix?

**Comment by adq82** [comment]
Również mam problem opisany przez HeartandHana. Czy jest szansa na poprawienie?

**Comment by kmalmur** [comment]
I found a solution for this. The addon is using `anyconfig` python module, which now only works with Python 3.X. This addon is working with python 2.7. So I just fixed Dokerfile to use the specific "old" version of `anyconfig`

I fixed this issue in my fork as the author doesn't seem to maintain this repository. Here is the link: https://github.com/kmalmur/hassio-addons

To install the addon from my fork, you need to add address to my repository in Home Automation instead of this one
